[2022-03-15 10:35:10,996] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-03-15T10:35:09.781511+00:00 [queued]>
[2022-03-15 10:35:11,006] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-03-15T10:35:09.781511+00:00 [queued]>
[2022-03-15 10:35:11,007] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 10:35:11,007] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-15 10:35:11,007] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 10:35:11,025] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): load_seed_data_once> on 2022-03-15 10:35:09.781511+00:00
[2022-03-15 10:35:11,030] {standard_task_runner.py:52} INFO - Started process 790 to run task
[2022-03-15 10:35:11,032] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', '1_init_once_seed_data', 'load_seed_data_once', 'manual__2022-03-15T10:35:09.781511+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/init.py', '--cfg-path', '/tmp/tmpe0g96zs1', '--error-file', '/tmp/tmpu6zv51yj']
[2022-03-15 10:35:11,032] {standard_task_runner.py:77} INFO - Job 63: Subtask load_seed_data_once
[2022-03-15 10:35:11,080] {logging_mixin.py:109} INFO - Running <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-03-15T10:35:09.781511+00:00 [running]> on host dd3c58b082a3
[2022-03-15 10:35:11,184] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=1_init_once_seed_data
AIRFLOW_CTX_TASK_ID=load_seed_data_once
AIRFLOW_CTX_EXECUTION_DATE=2022-03-15T10:35:09.781511+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-15T10:35:09.781511+00:00
[2022-03-15 10:35:11,185] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-15 10:35:11,185] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /dbt && dbt seed --profiles-dir .']
[2022-03-15 10:35:11,195] {subprocess.py:85} INFO - Output:
[2022-03-15 10:35:14,161] {subprocess.py:89} INFO - Running with dbt=0.20.0
[2022-03-15 10:35:16,709] {subprocess.py:89} INFO - Found 5 models, 0 tests, 0 snapshots, 0 analyses, 338 macros, 0 operations, 3 seed files, 0 sources, 0 exposures
[2022-03-15 10:35:16,711] {subprocess.py:89} INFO - 
[2022-03-15 10:35:18,674] {subprocess.py:89} INFO - 10:35:18 | Concurrency: 200 threads (target='dev')
[2022-03-15 10:35:18,674] {subprocess.py:89} INFO - 10:35:18 |
[2022-03-15 10:35:18,693] {subprocess.py:89} INFO - 10:35:18 | 1 of 3 START seed file public.bookings_1............................. [RUN]
[2022-03-15 10:35:18,693] {subprocess.py:89} INFO - 10:35:18 | 2 of 3 START seed file public.bookings_2............................. [RUN]
[2022-03-15 10:35:18,694] {subprocess.py:89} INFO - 10:35:18 | 3 of 3 START seed file public.customers.............................. [RUN]
[2022-03-15 10:35:18,790] {subprocess.py:89} INFO - * Deprecation Warning: The quote_columns parameter was not set for seeds, so the
[2022-03-15 10:35:18,790] {subprocess.py:89} INFO - default value of False was chosen. The default will change to True in a future
[2022-03-15 10:35:18,791] {subprocess.py:89} INFO - release.
[2022-03-15 10:35:18,791] {subprocess.py:89} INFO - 
[2022-03-15 10:35:18,791] {subprocess.py:89} INFO - For more information, see:
[2022-03-15 10:35:18,791] {subprocess.py:89} INFO - https://docs.getdbt.com/v0.15/docs/seeds#section-specify-column-quoting
[2022-03-15 10:35:20,674] {subprocess.py:89} INFO - 10:35:20 | 3 of 3 OK loaded seed file public.customers.......................... [[32mINSERT 2[0m in 1.98s]
[2022-03-15 10:35:20,754] {subprocess.py:89} INFO - 10:35:20 | 2 of 3 OK loaded seed file public.bookings_2......................... [[32mINSERT 7[0m in 2.06s]
[2022-03-15 10:35:20,982] {subprocess.py:89} INFO - 10:35:20 | 1 of 3 OK loaded seed file public.bookings_1......................... [[32mINSERT 7[0m in 2.29s]
[2022-03-15 10:35:21,564] {subprocess.py:89} INFO - 10:35:21 |
[2022-03-15 10:35:21,564] {subprocess.py:89} INFO - 10:35:21 | Finished running 3 seeds in 4.85s.
[2022-03-15 10:35:21,580] {subprocess.py:89} INFO - 
[2022-03-15 10:35:21,580] {subprocess.py:89} INFO - [32mCompleted successfully[0m
[2022-03-15 10:35:21,580] {subprocess.py:89} INFO - 
[2022-03-15 10:35:21,580] {subprocess.py:89} INFO - Done. PASS=3 WARN=0 ERROR=0 SKIP=0 TOTAL=3
[2022-03-15 10:35:22,782] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-15 10:35:22,804] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=1_init_once_seed_data, task_id=load_seed_data_once, execution_date=20220315T103509, start_date=20220315T103510, end_date=20220315T103522
[2022-03-15 10:35:22,848] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-15 10:35:22,883] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
